**Creating contingency table for computing statistical significance**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from statsmodels.stats.contingency_tables import mcnemar
from scipy.stats import ttest_ind
from scipy.stats import ks_2samp
from sklearn import metrics
import csv

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


**1. Contingency table for MC-EffNet-2 vs. Best baseline**

In [ ]:
file1 = open('path to MC-EffNet-2 prediction csv file')# our model
csvreader = csv.reader(file1)
mceffnet2 = []
for row in csvreader:
  mceffnet2.append(row)

print(len(mceffnet2))

file2 = open('path to best baseline prediction csv file')#InceptionResnet
csvreader = csv.reader(file2)
inception_resnet = []
for row in csvreader:
        inception_resnet.append(row)
print(len(inception_resnet))

2400
2400


In [ ]:
contingency_table_mceffnet2_with_baseline = metrics.confusion_matrix(mceffnet2, inception_resnet)
print("COntigency table mceffnet with best baseline \n",contingency_table_mceffnet2_with_baseline)

COntigency table mceffnet with best baseline 
 [[670  55 109]
 [101 503 145]
 [111 123 583]]


**2. Contingency table for MC-EffNet-2 vs. Manual Annotations**

In [ ]:
############# Manual annotation significance #############
file3 = open('path to MC-EffNet-2 prediction csv file')#
csvreader = csv.reader(file3)
psycho_mceffnet2 = []
for row in csvreader:
  psycho_mceffnet2.append(row)

print(len(psycho_mceffnet2))

file4 = open('path to manual prediction csv file')#
csvreader = csv.reader(file4)
psycho_manual = []
for row in csvreader:
        psycho_manual.append(row)
print(len(psycho_manual))

330
330


In [ ]:
contingency_table_psycho_mceffnet2_with_manual = metrics.confusion_matrix(psycho_mceffnet2, psycho_manual)
print("COntigency table Psycho Experiments \n",contingency_table_psycho_mceffnet2_with_manual)

COntigency table Psycho Experiments 
 [[49 35 40]
 [ 9 63 25]
 [16 29 64]]


**3. Contingency table for MC-EffNet-2 vs. SC-EffNet_RGB**

In [ ]:
print(len(mceffnet2)) #mceffnet2 already read

file5 = open('path to SC-EffNet_RGB prediction csv file')#
csvreader = csv.reader(file5)
sc_effnet_rgb = []
for row in csvreader:
        sc_effnet_rgb.append(row)
print(len(sc_effnet_rgb))

2400
2400


In [ ]:
contingency_table_psycho_mceffnet2_with_sc_effnet_rgb = metrics.confusion_matrix(mceffnet2, sc_effnet_rgb)
print("COntigency table MCEffnet with SCEffnet RGB \n",contingency_table_psycho_mceffnet2_with_sc_effnet_rgb)

COntigency table MCEffnet with SCEffnet RGB 
 [[694  57  83]
 [ 79 532 138]
 [116 144 557]]
